# Generated by Django 2.2.1 on 2019-12-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iot_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem', models.TextField()),
                ('hum', models.TextField()),
                ('somken', models.TextField()),
                ('mea', models.TextField()),
                ('door', models.TextField()),
                ('winzhu', models.TextField()),
                ('winci', models.TextField()),
                ('people', models.TextField()),
                ('cpu', models.TextField()),
            ],
        ),
    ]
